### ISSUE TITLE
AliasMap method

### ISSUE THREAD

**Issue by eddielee394** [IsraelOrtuno/permalink#10]
Is the reference to the `aliasMap()` method in the docs a typo?  Should it be `actionMap()` instead?  I don't see any static methods in the package referencing the `aliasMap` method.  
https://github.com/IsraelOrtuno/permalink#support-for-morphmap--aliasmap

**Comment by IsraelOrtuno** [comment]
Really sorry, I did the docs and then decided to change the name, will update

**Comment by eddielee394** [comment]
No need to apologize, this is an awesome package and the architecture is really well designed.   I'm happy i could help catch some of these small things.
