### ISSUE TITLE
Feature Idea - Permalink specific route name aliases

### ISSUE THREAD

**Issue by eddielee394** [IsraelOrtuno/permalink#12]
What would you think about the ability to add a route name alias to an individual record without requiring  an explicit declaration of the entity Id? This would be useful in development workflows where the database entries aren't always going to be in sync from environment to environment.  
For example, I encountered an issue where I was using the permalink route name to reference a specific page (i.e. `route(permalink.42)`) on a local environment.  This creates an issue if that id value doesn't exist in the other environment databases.   Even if we created a seed file for modifications made to the permalinks table to ensure it's kept up to date across all env's, the issue then would be potential conflicts with the changes made to the table's current index (id in this case).  Not to mention, generally speaking that would just add another step to the development workflow.
  
I initially considered three workarounds to deal with the issue currently:  
1.  explicitly reference the slug with:  `url('my-permalink-parent', 'my-permalink-child')` in the view; 
2.   Query the page object by slug within the controller and then passing the object as variable to the view where i could use the default `$page->route` method.  
3. Use an alias/action map.  

The first two workarounds were not really ideal as they used the hard-coded page slugs as primary point of reference - which means if the slug changes, we'd return an error.  If we needed to modify the reference in any way, it would require us to go back and modify the code which isn't very scalable and gets cumbersome when dealing with constantly having to go through build & deployment pipelines, etc.   
The third workaround would require a unique action for the referenced entry, which i think defeats the purpose of the dynamic nature of the package.  

So i was thinking it might smooth things out if we could assign a route name to an individual record, so in these instances we could just use something like:  `route('permalink.my_permalink_child')`.   Then we'd only have to make sure that route name exists in the Permalink table for it's respective entry, regardless of what that entry's id value happens to be.

Maybe it can be included in the "custom name column" idea mentioned in https://github.com/IsraelOrtuno/permalink/issues/5 
What do you think?

**Comment by IsraelOrtuno** [comment]
Will dig into this 👍

**Comment by IsraelOrtuno** [comment]
Due permalinks table is supposed to no be extensively used (as it's supposed to be cached and all), may be a good idea to include an "options" column. Maybe we could include a route name and middleware name in that column, what do you think? So we avoid that many null values as most permalinks won't need that (I guess).

**Comment by IsraelOrtuno** [comment]
> For example, I encountered an issue where I was using the permalink route name to reference a specific page (i.e. route(permalink.42)) on a local environment. 

Actually this is a common issue in any database driven routing system... If your permalinks are bound to models, you could use:

```php
$model->route;
```

To access its route without having to use the `route` function.

Really thinking about how to deal with this but not simple at all.

**Comment by IsraelOrtuno** [comment]
Also if you have an actionMap for a certain controller:

```php
'pricing' => 'App\Http\Controllers\PricingController@index'
```

The route will be named 'pricing', would that help you?

**Comment by IsraelOrtuno** [comment]
I am already working on a `options` JSON column which will be merged to parent options. This options may contain a `name` attribute.
