### ISSUE TITLE
Default parent_id on models

### ISSUE THREAD

**Issue by martin-ro** [IsraelOrtuno/permalink#15]
Hi,

great package! Was looking for a while for something like this and stumbled about your package in this [Medium](https://medium.com/@SlyFireFox/the-power-of-laravels-route-defaults-for-making-root-level-seo-pages-ae6da1d9fd51) article.

I have a model Pages and one Category, each Page belongs to one Category and Categories can have many Pages.

I have a factory to seed Pages like this:
```php
$factory->define(Page::class, function (Faker $faker) {

    $title = $faker->sentence(rand(3, 7));
    $category = Category::all()->random();

    return [
        'title' => substr($title, 0, strlen($title) - 1),
        'category_id' => $category->id,
        'permalink' => [
            'parent_id' => $category->permalink->permalinkable_id,
        ],
    ];
});
```

This works all fine but I'm wondering how to tell my Page model to always use the category it belongs to as `parent_id`?

**Comment by IsraelOrtuno** [comment]
Umm this is a bit confusing, you are giving the `permalinkable_id` as `parent_id` but that `permalinkable_id` is the primary key of the Category, not the Permalink. That `permalink_id` should get:

```php
        'permalink' => [
            'parent_id' => $category->permalink->id,
        ],
```

Then if you want this automatic, you could try to do something like this in your model:

```php
public static function boot() {
    static::creating(function($model) {
        if ($model->parent_id) {
            return;
        }

        $model->permalink = ['parent_id' => $model->category->permalink->id];
    });
}
```

Haven't tested the code, but should look something similar :)

**Comment by IsraelOrtuno** [comment]
Be aware this package is under active development. Use only the tagged versions as others are pretty unstable.

The package has been mainly rewritten in the `develop` branch which will get a huge performance improvement.

**Comment by martin-ro** [comment]
Thanks, that worked:

```
public static function boot() {

        parent::boot();

        static::creating(function($model) {

            if ($model->parent_id) {
                return;
            }

            if (isset($model->category->permalink->id)) {
                $model->permalink = ['parent_id' => $model->category->permalink->id];
            }
        });
    }
```

**Comment by martin-ro** [comment]
Looking forward to the performance improvements.. for now I'm just tinkering around with it. Not in production

**Comment by IsraelOrtuno** [comment]
API won't change too much :)

Feel free to provide feedback/open issues, I would really appreciate.
