### ISSUE TITLE
How can make it work with multiple language ?

### ISSUE THREAD

**Issue by tuandev-nv** [IsraelOrtuno/permalink#20]
My website's using a [translatable package](https://github.com/spatie/laravel-translatable), so i save 'slug' field is json in database.
I don't know how to make multiple record in permalink table for one model record ?
Ex: 
EN language: mydomain.com/my-slug-in-en
FR language: mydomain.com/my-slug-in-fr
Thanks !

**Comment by IsraelOrtuno** [comment]
@estaticfear there are a couple of ways to achieve this but is not fully documented yet. I would be happy to help you via Skype/Telegram/Other if you wish to, let me know your preferred and I'll contact ;)

**Comment by tuandev-nv** [comment]
@IsraelOrtuno 
Thanks for your reply !
I'm have skype but my english so bad for a talk :(
If can, please create a short document, i can do it by myself. 
I think it's useful with someone, too :)
I'm using google translate, haha

**Comment by martin-ro** [comment]
I would be interested in a solution as well.. any chance to get an example in the documentation?

**Comment by IsraelOrtuno** [comment]
Ummm. The package is intended for having a single permalink per model record:

https://github.com/IsraelOrtuno/permalink/blob/master/src/HasPermalinks.php#L59

Taking this into account... Are you trying to use it with a database record or pointing the permalink to a controller action?

**Comment by martin-ro** [comment]
Sorry, I'm using https://github.com/dimsav/laravel-translatable.

**Comment by IsraelOrtuno** [comment]
Routing system has been widely rewritten, will test for packages compatibility and add documentation about it

**Comment by vildanbina** [comment]
is it useful if we add single column for language, and we access on it ?
