### ISSUE TITLE
Make compatible with Laravel ^6.0

### ISSUE THREAD

**Issue by martin-ro** [IsraelOrtuno/permalink#25]

**Comment by IsraelOrtuno** [comment]
What version are you using?

**Comment by IsraelOrtuno** [comment]
Versions 0.x are not longer maintained, the package has been widely rewritten and it's way more powerful now. Would you consider switching to the `dev-master` branch? It supports L6.

**Comment by martin-ro** [comment]
Using 6.0 on that project. I switched to `dev-master`, looking all good now. 

Have you integrated the package with Nova? I'm trying to display the slug field on resource in Nova at the moment but can't figure it out.

**Comment by IsraelOrtuno** [comment]
Could you share a bit of code? Haven't had the opportunity to try Nova yet

**Comment by martin-ro** [comment]
Figured it out. 

It's possible to display the slug using a Nova Text field through the relationship. Even more convenient: [benjaminhirsch/nova-slug-field](https://github.com/benjaminhirsch/nova-slug-field).

Example:

`App\Nova\Page.php`

```
use Benjaminhirsch\NovaSlugField\Slug;
use Benjaminhirsch\NovaSlugField\TextWithSlug;

TextWithSlug::make('Title')
                ->slug('permalink')
                ->sortable()
                ->rules('required', 'max:255'),

            Slug::make('Permalink')
                ->showUrlPreview(config('app.url'))
                ->sortable()
                ->rules('required', 'max:255')
                ->displayUsing(function () {
                    return isset($this->permalink) ? $this->permalink->slug : '';
                })
                ->withMeta(['value' => $this->permalink->slug ?? ''])
                ->disableAutoUpdateWhenUpdating(),
```

For creating and updating the model i simply use a model observer.

`App\Observers\PageObserver.php`

```
public function creating(Page $page)
    {
        $page->permalink = ['slug' => request()->permalink];
    }

    public function updating(Page $page)
    {
        $page->permalink = ['slug' => request()->permalink];
    }
```

**Comment by IsraelOrtuno** [comment]
I am glad you made it work. Be aware you made it work 👍. I hope you find the package useful...

Are you using the SEO options or just the routing? (Curious about how others use it)

**Comment by martin-ro** [comment]
Very useful, great work! It has become my to go package for the last 4 projects.

I haven't used SEO functionality yet. I normally use [artesaos/seotools](https://github.com/artesaos/seotools). But I probably will check it out some time.

**Comment by IsraelOrtuno** [comment]
This package uses other package for generating the HTML tags but you can define the information into your `permalinks` table, so it will automatically generate this content:

Check this out, may be helpful! https://github.com/IsraelOrtuno/permalink#handling-seo-attributes
