### ISSUE TITLE
Fail back to normal routes?

### ISSUE THREAD

**Issue by elfeffe** [IsraelOrtuno/permalink#27]
Is fail back supported?

**Comment by IsraelOrtuno** [comment]
What do you mean by fallback?

**Comment by elfeffe** [comment]
I mean, if it doesn't find the URL, will continue with normal Laravel routes?

**Comment by IsraelOrtuno** [comment]
Yes it does 👍

**Comment by IsraelOrtuno** [comment]
In fact Laravel routes have preference:

https://github.com/IsraelOrtuno/permalink/blob/master/tests/Feature/Routing/RoutingTest.php#L48-L58
