### ISSUE TITLE
Consider adding middleware support

### ISSUE THREAD

**Issue by IsraelOrtuno** [IsraelOrtuno/permalink#3]
What about adding middleware support to parent routes. Maybe by single permalink record

**Comment by Kalifr** [comment]
Peace friends, Is there a way I can add a middleware at least on nested routes?
Thank you.

**Comment by IsraelOrtuno** [comment]
I am afraid not. You could however add it to the constructor of controller that resolves your route. Unless you are looking to add a middleware to a specific route, that should help 😅

**Comment by Kalifr** [comment]
Thanks, that works. It's a beautiful package you got here. Thank you.

> I am afraid not. You could however add it to the constructor of controller that resolves your route. Unless you are looking to add a middleware to a specific route, that should help
