### ISSUE TITLE
Supported Naming Conventions for SEO Field

### ISSUE THREAD

**Issue by eddielee394** [IsraelOrtuno/permalink#7]
What are the supported input naming conventions for auto updating the SEO field json objects?  I was able to find a few of them in the undocumented permalink_forms repo i.e. `permalink[seo][advanced][robots][index]`.  But wasn't sure if there are others, specifically for like opengraph and twitter tags.

**Comment by IsraelOrtuno** [comment]
Still need to document that part but you can use `title` and `description` for now
