### ISSUE TITLE
Question - Output SEO values in view

### ISSUE THREAD

**Issue by eddielee394** [IsraelOrtuno/permalink#8]
Is there a built in helper method to display the SEO data in a view?  For example, the arcane package uses the `seo_helper()->render()` method.  Is there anything like that in this package?  Or do I have to write my own methods to display the seo data?

**Comment by IsraelOrtuno** [comment]
@eddielee394 this is not documented yet but this package uses that powerful package to finally render the HTML. Use that method to render your SEO :)

**Comment by IsraelOrtuno** [comment]
Btw would love feedback :D

**Comment by eddielee394** [comment]
I know you're still working on the docs for this, but could you provide me with a bit clearer starting point with passing the SEO params to the view?  I can't seem to get the SEO params passed to the view, without explicitly declaring them in my controller method.  I looked at the `Builder` class and it seems that they should automatically be passed to the seohelper once the request is made.  But, i can't seem to get that to work, as the `seohelper->render()` method in my view just returns the default values set in the arcane config file.    
If you can help me get a better handle on how the package should be outputting the seo stuff, i'd be more than happy to contribute to writing up the docs for ya.

**Comment by eddielee394** [comment]
Did some additional testing with this & was able to get the SEO Builder working after overcoming a few caveats.  
- Needed to add `\Devio\Permalink\Middleware\BuildSeo::class`
 middleware to the `Http\Kernel` class.  
- Needed to remove the default arcane config file, as it was overriding the permalink params.  

I'll submit a pull request with a few notes for the docs this weekend.

**Comment by IsraelOrtuno** [comment]
Yes, you have to add that middleware to your HTTP Kernel. I did not know that the default arcane config file was overriding, will check that out. Once you have this set and the `seo_helper()->render()` in your `head` tag, the permalink matching your current view should have the following JSON structure on the SEO column:

```
{
  meta: {
    title: 'Hello',
    description: 'Description',
    robots: 'noindex'
  }
}
```

Opengraph and Twitter cards will be available soon too

**Comment by IsraelOrtuno** [comment]
@eddielee394 added documentation about SEO, let me know if it's clear enough!

**Comment by eddielee394** [comment]
Docs seem clear enough to me.  I didn't realize the you could register your own custom builder class in the container, which is pretty cool because I initially was just using a custom trait that inherited the `seoable` class.

**Comment by IsraelOrtuno** [comment]
By registering your own builders you can replace the entire meta generation classes to other package or however you like :)
